---
outlines:
    default: { width: 52, height: 56 }
    action:  { width: 95, height: 56 }
    altline: { width: 76, height: 56 }
    wide: { width: 66, height: 56 }
    spaceline: { width: 220, height: 56 }
    special: { width: 60, height: 56 }
    small: { width: 56, height: 44 }

views:
    base:
        - "Esc Tab Ctrl Alt Slash Pipe ↑ ↓ ← →"
        - "q w e r t y u i o p å"
        - "a s d f g h j k l ö ä"
        - "Shift_L < z x c v b n m  BackSpace"
        - "show_numbers preferences      space      period show_actions Return"
    upper:
        - "Esc Tab Ctrl Alt Slash Dash PgUp PgDn SmallHome SmallEnd"
        - "Q W E R T Y U I O P Å"
        - "A S D F G H J K L Ö Ä"
        - "Shift_L > Z X C V B N M  BackSpace"
        - "show_numbers preferences      space      colon show_actions Return"
    numbers:
        - "Esc Tab Ctrl Alt Slash Pipe ↑ ↓ ← →"
        - "1 2 3 4 5 6 7 8 9 0"
        - "* # $ / & - _ + ( )"
        - "show_symbols   , \" ' : ; ! ?  BackSpace"
        - "show_letters preferences         space        period Return"
    symbols:
        - "Esc Tab Ctrl Alt Slash Pipe ↑ ↓ ← →"
        - "~ ` | · √ π τ ÷ × ¶"
        - "© ® £ € ¥ ^ ° @ { }"
        - "show_numbers_from_symbols   \\ % < > = [ ]  BackSpace"
        - "show_letters preferences         space        period Return"
    actions:
        - "Esc Tab Ctrl Alt Slash Pipe PgUp PgDn SmallHome SmallEnd"
        - "F1  F2  F3  F4  F5  F6"
        - "F7  F8  F9  F10 F11 F12"
        - "Pause Insert Del Home Up End"
        - "show_letters Menu Break Left Down Right"

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: erase
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "altline"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "wide"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "altline"
        label: "τ=\\"
    show_actions:
        action:
            set_view: "actions"
        outline: "altline"
        label: ">_"
    period:
        outline: "altline"
        text: "."
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "wide"
        icon: "key-enter"
        keysym: "Return"
    colon:
        outline: "altline"
        text: ":"
    F1:
        outline: "action"
        keysym: "F1"
    F2:
        outline: "action"
        keysym: "F2"
    F3:
        outline: "action"
        keysym: "F3"
    F4:
        outline: "action"
        keysym: "F4"
    F5:
        outline: "action"
        keysym: "F5"
    F6:
        outline: "action"
        keysym: "F6"
    F7:
        outline: "action"
        keysym: "F7"
    F8:
        outline: "action"
        keysym: "F8"
    F9:
        outline: "action"
        keysym: "F9"
    F10:
        outline: "action"
        keysym: "F10"
    F11:
        outline: "action"
        keysym: "F11"
    F12:
        outline: "action"
        keysym: "F12"
    Del:
        outline: "action"
        keysym: "Delete"
    Insert:
        outline: "action"
        keysym: "Insert"
    Menu:
        outline: "action"
        keysym: "Menu"
    Pause:
        outline: "action"
        keysym: "Pause"
    Break:
        outline: "action"
        keysym: "Break"
    Home:
        outline: "action"
        keysym: "Home"
    End:
        outline: "action"
        keysym: "End"
    PgUp:
        outline: "small"
        keysym: "Page_Up"
    PgDn:
        outline: "small"
        keysym: "Page_Down"
    "↑":
        outline: "small"
        keysym: "Up"
    "↓":
        outline: "small"
        keysym: "Down"
    "←":
        outline: "small"
        keysym: "Left"
    "→":
        outline: "small"
        keysym: "Right"
    Up:
        label: "↑"
        outline: "action"
        keysym: "Up"
    Left:
        label: "←"
        outline: "action"
        keysym: "Left"
    Down:
        label: "↓"
        outline: "action"
        keysym: "Down"
    Right:
        label: "→"
        outline: "action"
        keysym: "Right"
    Ctrl:
        label: "Ctrl"
        outline: "small"
        modifier: "Control"
    Alt:
        label: "Alt"
        outline: "small"
        modifier: "Alt"
    Esc:
        keysym: "Escape"
        outline: "small"
    Tab:
        keysym: "Tab"
        outline: "small"
    Slash:
        label: "/"
        outline: "small"
        text: "/"
    Dash:
        label: "-"
        outline: "small"
        text: "-"
    Pipe:
        label: "|"
        outline: "small"
        text: "|"
    SmallHome:
        label: "Home"
        outline: "small"
        keysym: "Home"
    SmallEnd:
        label: "End"
        outline: "small"
        keysym: "End"

